### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [JonasBernard/TU-Darmstadt-Moodle-Wrapper#1]
You can add Screenshots for F-Droid, too, if you want. https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ https://gitlab.com/snippets/1895688 That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by JonasBernard** [comment]
Hi! Thanks for that tip. I don't know what to screenshot there. I dont have any activities. The feature graphic explains the concept.
If you have applicable screenshots, you can post them here.
