### ISSUE TITLE
exam moodle does not open

### ISSUE THREAD

**Issue by JohaJung** [JonasBernard/TU-Darmstadt-Moodle-Wrapper#3]
Hi Jonas, great and useful app, thank's!

The exam moodle link binding does not work for me (Samsung, Android 13). From a quick glance into the code, this bug could be due to the trailing slash in this line? https://github.com/JonasBernard/TU-Darmstadt-Moodle-Wrapper/blob/91e91516abd7c87c370cc69d9ed7b284cca6d430/app/src/main/AndroidManifest.xml#L51

**Comment by JonasBernard** [comment]
Oh thanks, that's probably the right line to fix it.
I'll fix it later today.
It will take quite a while until an update appears on F-Droid.
